name: daylog
description: "A new Flutter project."
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=3.5.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  firebase_core: ^3.8.1
  firebase_auth: ^5.3.4
  cloud_firestore: ^5.5.1
  cloud_functions: ^5.1.3
  firebase_storage: ^12.3.7
  google_sign_in: ^6.2.2
  kakao_flutter_sdk_user: ^1.9.1
  flutter_riverpod: ^2.6.1
  riverpod_annotation: ^2.6.1
  flutter_svg: ^2.0.17
  go_router: ^14.6.2
  json_annotation: ^4.9.0
  flutter_dotenv: ^6.0.0
  google_fonts: ^8.0.1
  kakao_flutter_sdk: ^1.10.0
  google_generative_ai: ^0.4.7
  image_picker: ^1.2.1
  camera: ^0.11.0+2
  uuid: ^4.5.2
  flutter_hooks: ^0.21.3+1
  hooks_riverpod: ^2.6.1
  cached_network_image: ^3.4.1
  intl: ^0.20.2
  freezed_annotation: ^2.4.4
  marquee: ^2.3.0
  url_launcher: ^6.3.1
  shared_preferences: ^2.5.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  build_runner: ^2.4.13
  riverpod_generator: ^2.6.3
  freezed: ^2.5.7
  json_serializable: ^6.9.0

flutter:
  uses-material-design: true
  assets:
    - .env
    - assets/images/
    - assets/svgs/
